### ISSUE TITLE
[Bug] CVar pug_timeleft causes intro HUD message to not appear

### ISSUE THREAD

**Issue by 1719calvin** [SmileYzn/CS_PugMod-Archive#1]
If i add pug_timeleft in amxx.cfg, ( for example pug_timeleft = 150), the intro message ( Welcome to <hostname> /n You must type !add...) is shown for a split second before the information window opens. After closing the window the message does not reappear.

Running updated HLDS beta on linux with amxmodx v 1.8.2. Plugin version 1.1.6

@SmileYzn

**Comment by SmileYzn** [comment]
CVar pug_timeleft does not exists, you need to be more specific if you chanded / added any code to pug.

**Comment by 1719calvin** [comment]
I did not change any code, other than changing the prefix macro. How do you mean this cvar does not exist? if I use amx_automix_settings cmd as admin, in the menu there this CVar is present. Are you saying that this cvar can only be changed from the menu, and I cannot add it to amxx.cfg? Because this is problematic, as the value got reset to default at every map change.

**Comment by SmileYzn** [comment]
Man read readme.md, such cvar does not exists (See in amxmodx/configs/pug.rc)

This plugin is NOT AutoMix, is my CS PugMod (Originaly developed by Rukia)
