### ISSUE TITLE
Error start server

### ISSUE THREAD

**Issue by albastrel** [SmileYzn/CS_PugMod-Archive#10]
L 07/24/2015 - 14:56:03: Called dynanative into a paused plugin.
L 07/24/2015 - 14:56:03: [AMXX] Displaying debug trace (plugin "PugCore.amxx", version "2.0.0")
L 07/24/2015 - 14:56:03: [AMXX] Run time error 10: native error (native "PugGetPlayers")
L 07/24/2015 - 14:56:03: [AMXX]    [0] PugCore.sma::client_authorized (line 170)
L 07/24/2015 - 14:56:09: Called dynanative into a paused plugin.
L 07/24/2015 - 14:56:09: [AMXX] Displaying debug trace (plugin "PugReady.amxx", version "2.0.0")
L 07/24/2015 - 14:56:09: [AMXX] Run time error 10: native error (native "PugIsTeam")
L 07/24/2015 - 14:56:09: [AMXX]    [0] PugReady.sma::PugReadyDisPlay (line 180)
L 07/24/2015 - 14:56:09: [AMXX]    [1] PugReady.sma::PugKeepMenu (line 163)
L 07/24/2015 - 14:56:09: [AMXX]    [2] PugReady.sma::client_putinserver (line 55)

hmm ?

**Comment by SmileYzn** [comment]
Into a paused plugin, simple un-pause it.

**Comment by perforatorRU** [comment]
Dude you where gone? We all care! Do not leave your mod! Please!
