### ISSUE TITLE
Some features you should add.

### ISSUE THREAD

**Issue by abhishekdeshkar** [SmileYzn/CS_PugMod-Archive#14]
Hello,

You should really add these features.

1) Instead of only .hp .dmg also access to /hp /dmg. I mean / for all commands.
2) Enable to disable Auto team selection when player connects. Auto Team selection is what I want everytime.
3) Auto ready is not working after vote map and map changes. Auto ready should work in every situation. I have set to 10 but in some case after match ends and then match starts, it doesn't work.

**Comment by SmileYzn** [comment]
1. The mod runs on **.** Sorry but you can changet it on source, since i will never do 😀 
2. The mod already balance the teams before start map vote, make auto-join management do not make any sense.
3. Ready system have cvars to this, check it

**Comment by ghost** [comment]
@SmileYzn Ready System has Bugs i guess , As @abhishekdeshkar Mentioned above on Restart ( When a Match gets over ) Some players Get Ready but some didnt !!
I have my Settings on AUTO already :
pug_force_ready_time "5.0"
pug_force_ready_kick   "0"

But still it doesnt work on Map change 
( Works Perfectly Before PUG START )

**Comment by SmileYzn** [comment]
I will try to review this, i am thinking to rewrite whole mod using csgo style.

**Comment by mechelin97** [comment]
é uma ótima idéia.

2017-09-20 12:57 GMT+01:00 Cleverson <notifications@github.com>:
