### ISSUE TITLE
Won't Compile

### ISSUE THREAD

**Issue by KittenKassarole** [SmileYzn/CS_PugMod-Archive#15]
When I pull the latest version of this plugin and attempt to compile (being sure to use the include files) I receive nothing but errors: 
error 017: undefined symbol "create_cvar"

This happens when attempting to compile all the sma files.  Please help, I would love to use this mod for my Clan's pug server.  

Thanks!

**Comment by deepaklost** [comment]
compile it in amxmodx 1.8.3 ... u must be using 1.8.2 version ...

**Comment by KittenKassarole** [comment]
I was using the latest build version from here: http://www.amxmodx.org/downloads.php which is 1.8.2

Once I switched to using 1.8.3-dev-git5095 it was able to compile.  However, when I added the various files to the server nothing happened.  The server was running 1.8.3-dev-git4037 and I had to manually FTP files to upgrade to 1.8.3-dev-git5095 and now things seem to be running correctly.

**Comment by SmileYzn** [comment]
You need to compile on 1.8.3 hg5100+ also use the same version on server bro.
