### ISSUE TITLE
HLTV Auto Record Demo

### ISSUE THREAD

**Issue by KittenKassarole** [SmileYzn/CS_PugMod-Archive#16]
I am trying to find a way to auto-record HLTV demos of pugs.  Looking in the CVAR section I see reference to HLTV:

pug_hltv_host	- Remote HLTV IP address
pug_hltv_port	- Remote HLTV Port
pug_hltv_pass	- Remote HLTV (Rcon|adminpass) Password
pug_hltv_demo_dir	- Demos sub-dir (Stored at cstrike folder)
pug_hltv_demo_name	- Demo name prefix (Ie. pug will be saved as pug-1504070051-de_dust2.dem)

However, looking in the actual pugmod.rc file it doesn't look like these are included?  

Questions
- If these CVAR settings are entered does the mod to auto record pugs?
- Do you have to enter a demo sub-dir? 
- If using a separate HLTV would the demos be located under the HLTV or Game Server? 

I appreciate any info or examples you can provide.  The mod has been working great for our Pugs!

**Comment by SmileYzn** [comment]
Look at releases section (In 2.0.1 version to be exact), You can found the source of HLTV plugin to use on server.

Also i stopped to update here on these days duo new version. On next release i can re-add.

**Comment by Slinfy97** [comment]
@SmileYzn waiting for full update along with PugDB/Stats/HLTV if you need any help with testing im always open for help.  :)
