### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by Disqual** [SmileYzn/CS_PugMod-Archive#18]
Didn't find any other section to contact you.
First of all, you've been making such a great job for doing this.
Anyway, I was wondering that does it need a lot of work to make this work from a website? Players would join to pug on website and after it has reached 10 players it would randomly choose 2 captains and those pick players for their teams. And after that there would be a map vote and then when everything is ready to go the website would give IP:PW

**Comment by SmileYzn** [comment]
IT can be done, but need a whole web / front end site to do it.

Can you contact-me?

SmileYzn@live.com at Skype
