### ISSUE TITLE
cvars.htm & pugmode.rc, request to make descriptions more specific

### ISSUE THREAD

**Issue by Gh0stMan** [SmileYzn/CS_PugMod-Archive#3]
1. pugmode.rc contains "pug_acess_mode" while cvar.htm contains "pug_access_mode". Also description of this cvar is no so clear.
2. "pug_players_min_default" and "pug_players_max_default" description in cvar.htm is not very clear. It says "Minimum/maximum players to reset". To reset what? Maybe with these cvars you set min number of players needed to start pug and max number of players allowed to server (maybe I'm wrong)? 
3. What's the difference between "pug_intermission_time" and "pug_switch_delay". Maybe you could make descriptions of these commands in cvar.htm more clear?
4. "pug_vote_delay" also has not very clear description. In cvar.htm it says "Delay to end a vote". Maybe you could specify which vote?
5. Also, many cvars are missing on your github readme.md file, under title ".convars (Needs to be updated)".

**Comment by SmileYzn** [comment]
Thanks for reporting, my english is not soo good and i am not trying to make a larger descriptions. But i need to make more clear as possible,

**Comment by SmileYzn** [comment]
Will be fixed at last Pug Mod update.
