### ISSUE TITLE
Error when executing MySQL 'pug_match' table code

### ISSUE THREAD

**Issue by Gh0stMan** [SmileYzn/CS_PugMod-Archive#4]
I get error when executing MySQL code to create 'pug_match' table. > http://prntscr.com/6xqy1a
Error sound like this "#1067 - Invalid default value for 'date'"

**Comment by SmileYzn** [comment]
Update MySQL Version or PhpMyAdmin version, i will add the required versions to readme.md.

Until i do this, i will stay this issue opened.

**Comment by SmileYzn** [comment]
Yes, is MySQL Version needs to be 5.5+
