### ISSUE TITLE
'pug_players_min', 'pug_players_min' & 'pug_vote_map' are not included in pugmode.rc file

### ISSUE THREAD

**Issue by Gh0stMan** [SmileYzn/CS_PugMod-Archive#6]
'pug_players_min', 'pug_players_min' & 'pug_vote_map' are not included in pugmode.rc file. I found out about these commands by reviewing sma files.

**Comment by SmileYzn** [comment]
The reason for this is simple: You need to use max_players_default / min_players_defaut and pug_votemap_enabled.

The 'Lacking' cvars cannot be added to pugmod.rc specially the pug_vote_map, that is used only for internal check if the server will start a vote in the current map or not.

The cvars players_min|max is used for internal votes like old .voteplayers command (That i will add in future versions)

 :do_not_litter:
