### ISSUE TITLE
Error when executing 'PugProcedures.sql'

### ISSUE THREAD

**Issue by Gh0stMan** [SmileYzn/CS_PugMod-Archive#7]
Here is screen of error > http://prntscr.com/6xs1ll

It says "#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'iMax;
END' at line 6 "

**Comment by SmileYzn** [comment]
I will investigate this too, but seems to be a MySQL version from PhpMyAdmin.

I used last Xampp Version for Windows to test the procedures and tables.

**Comment by Gh0stMan** [comment]
If that helps here are phpmyadmin and mysql versions I'm using http://prntscr.com/6xycga

**Comment by SmileYzn** [comment]
I have used MySQL 5.5+. The pma version does not matter i guess.
