### ISSUE TITLE
plugin local ban

### ISSUE THREAD

**Issue by htm1994** [SmileYzn/CS_PugMod-Archive#8]
hello
i want add unbanmenu and ban ip this plugin
when amx_sxe_menu
select unban menu then show hadwar id in sxe local ban.cfg then select item remove from sxe local ban.cfg then unban
https://forums.alliedmods.net/showthread.php?t=186422

**Comment by SmileYzn** [comment]
CS PugMod not support sXe users until now.

Sorry bro.
